name: Verify Master Branch on Windows
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    paths:
      - '.github/workflows/verify_windows.yml'

jobs:
  build:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096
      INTEGRATION_TEST_GITHUB_TOKEN: ${{ secrets.INTEGRATION_TEST_GITHUB_TOKEN }}
      INTEGRATION_TEST_GITLAB_TOKEN: ${{ secrets.INTEGRATION_TEST_GITLAB_TOKEN }}
      INTEGRATION_TEST_BITBUCKET_TOKEN: ${{ secrets.INTEGRATION_TEST_BITBUCKET_TOKEN }}
      INTEGRATION_TEST_AZURE_TOKEN: ${{ secrets.INTEGRATION_TEST_AZURE_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      # Windows file operation slowness means there's no point caching this
      - name: yarn install
        run: yarn install --immutable

      - name: test
        run: yarn backstage-cli repo test --maxWorkers=2 --workerIdleMemoryLimit=1300M
        env:
          BACKSTAGE_TEST_DISABLE_DOCKER: 1
